runner.dialect = scala213source3
rewrite.scala3.convertToNewSyntax = false
style = defaultWithAlign
maxColumn = 80
align.preset = most
rewrite.rules = [Imports, SortModifiers]
rewrite.imports.sort = original
importSelectors = singleLine
docstrings.style = AsteriskSpace
docstrings.blankFirstLine = yes
docstrings.oneline = unfold
docstrings.wrap = unfold
version = 3.9.4